# Generated by Django 2.1.1 on 2018-09-14 02:04

from django.db import migrations
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_user_requested_friends'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='group',
            managers=[
                ('objects', main.models.GroupManager()),
            ],
        ),
    ]
