# Generated by Django 2.1.1 on 2018-09-15 04:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('main', '0008_auto_20180915_1018'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries_created', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='main.Group')),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries_initiated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='EntryParticipation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('type', models.CharField(choices=[('OWE', 'owe'), ('LENT', 'lent')], max_length=4)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Entry')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterModelOptions(
            name='bill',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'base_manager_name': 'objects'},
        ),
        migrations.RemoveField(
            model_name='bill',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='group',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='id',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='initiator',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='name',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='initiator',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='group',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='initiator',
        ),
        migrations.AddField(
            model_name='entry',
            name='participants',
            field=models.ManyToManyField(related_name='participating_entries', through='main.EntryParticipation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entry',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_main.entry_set+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='bill',
            name='entry_ptr',
            field=models.OneToOneField(auto_created=True, default=-1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.Entry'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='entry_ptr',
            field=models.OneToOneField(auto_created=True, default=-1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.Entry'),
            preserve_default=False,
        ),
    ]
