# Generated by Django 2.1.1 on 2018-09-15 07:24

from django.db import migrations
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20180915_1210'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='bill',
            managers=[
                ('objects', main.models.BillManager()),
            ],
        ),
        migrations.RenameField(
            model_name='debt',
            old_name='user2',
            new_name='other_user',
        ),
        migrations.RenameField(
            model_name='debt',
            old_name='user1',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='debt',
            name='type',
        ),
        migrations.RemoveField(
            model_name='entryparticipation',
            name='type',
        ),
    ]
