# Generated by Django 2.1.1 on 2018-09-16 11:39

from django.db import migrations
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20180915_1605'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='payment',
            managers=[
                ('objects', main.models.PaymentManager()),
            ],
        ),
    ]
