# Generated by Django 2.1.1 on 2018-09-24 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20180916_2216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debt',
            name='group',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='group',
        ),
        migrations.RemoveField(
            model_name='group',
            name='invited_users',
        ),
        migrations.AddField(
            model_name='bill',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='main.Group'),
        ),
    ]
