# Generated by Django 2.1.1 on 2018-09-25 01:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20180924_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='requested_friends',
            field=models.ManyToManyField(blank=True, related_name='received_friend_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
